// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fujhgxzuezrfjdcllbld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1amhneHp1ZXpyZmpkY2xsYmxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODY1MzYsImV4cCI6MjA2NjM2MjUzNn0.iQjdEzexSBWjJmGbRXIVGAcUVGW9wPMYs01Po5P4nJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);